exercises = [
    {
        "title": "Ab Crunch Machine",
        "equipment": "Full gym",
        "primary": ["Abs"],
        "secondary": [],
        "description": [
            "Sit on the ab machine and select a slight resistance. Position your feet under the pads and grab hold of the top handles.",
            "Make sure your arms are bent at 90 degrees and rest your triceps on the pads.",
            "Begin lifting your legs up as you engage your abs and crunch your upper torso. Exhale as you do so.",
            "Pause and slowly return to starting position as you inhale.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=30967&a=1",
    },
    {
        "title": "Ab Roller / Wheel Rollout / Kneeling Roll Extensions",
        "equipment": "Full gym",
        "primary": ["Abs"],
        "secondary": ["Biceps", "Shoulders"],
        "description": [
            "Kneel on the floor on all fours and place the ab roller in front of you.",
            "Grab hold of either end of the roller with each hand.",
            "Engage your abs and slowly roll the roller forward in a straight line until your body stretches in a straight position.",
            "Try to roll down as far as you can without touching the floor.",
            "Inhale in as you roll down.",
            "Pull yourself back to the starting position by exhaling and rolling back slowly. Maintain tight abs throughout the movement.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=30971&a=1",
    },
    {
        "title": "Alternate Heel Touches / Lying Oblique Reach",
        "equipment": "NO EQUIPMENT",
        "primary": ["Obliques"],
        "secondary": ["Abs"],
        "description": [
            "Lie on an exercise mat, with your back flat, knees bent and your feet flat on the floor slightly wider than shoulder-width apart.",
            "Fully extend your arms down the side of your body, palms facing in. This is the start position.",
            "Exhaling, crunch your torso forward and to the right until you can touch your right heel with your right hand. Hold for a count of one.",
            "Return to the starting position smooth motion, inhaling as you do so.",
            "Repeat the movement, this time to your left side.",
            "When you have completed the movement on both sides, you have done one repetition.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=30979&a=1",
    },
    {
        "title": "Barbell Windshield Wipers",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Abs"],
        "secondary": ["Shoulders"],
        "description": [
            "Hold a lightly-loaded barbell directly above your chest, and keep your back in full contact with the floor. ",
            "Lift both legs towards the left plate on the barbell and do your best to touch the plate lightly with your toes. ",
            "Lower both legs down to the central position being sure not to bounce them off the ground.",
            "Lift both legs towards the right plate on the barbell and do your best to touch the plate lightly with your toes.",
            "Lower both legs down to the central position; this completes one rep. ",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32727&a=1",
    },
    {
        "title": "Bicycles / Elbow-to-Knee Crunches / Cross-body Crunches",
        "equipment": "NO EQUIPMENT",
        "primary": ["Abs", "Obliques"],
        "secondary": ["Glutes & Hip Flexors", "Quadriceps"],
        "description": [
            "Lie flat on an exercise mat on the floor keeping your lower back straight with no arching of your spine and with your knees bent and feet flat on the floor.",
            "Place your hands lightly on the sides of your head.",
            "Curl your torso upwards so your shoulders are slightly raised off the floor..",
            "Raise your knees until your thighs are at a right angle to the floor and your calves are parallel to the floor. This is the start position.",
            "Slowly move your legs in a pedaling action as if you are riding a bicycle.",
            "As you do so, exhale and bring your opposing elbow close to each knee by crunching to one side. Left elbow to right knee. Right elbow to left knee.",
            "After each crunch, return to the start position inhaling as you do so.",
            "Without pausing, repeat the movement to the other side.",
            "Repeat without pausing for the desired number of repetitions to each side.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31163&a=1",
    },
    {
        "title": "Captain's Chair Leg / Knee / Hip Raises",
        "equipment": "Full gym",
        "primary": ["Abs"],
        "secondary": ["Lower Back"],
        "description": [
            "Place your forearms are on the pads or bars of the apparatus you are using and grip the handles or bars. Your arms should be bent at 90 degrees and your upper arms in a straight line with your sides.",
            "Your torso should be straight and your lower back pressed against the pad of the bench if using one.",
            "Keep your legs extended and pointing down to the floor. This is the start position.",
            "Exhale and as you do so, lift your legs up in a smooth arc bending at the knees until your thighs are about parallel to the floor. Hold for a count of one.",
            "Return to the start position in a smooth, controlled movement while inhaling.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31751&a=1",
    },
    {
        "title": "Crunches",
        "equipment": "NO EQUIPMENT",
        "primary": ["Abs"],
        "secondary": [],
        "description": [
            "Lie flat on your back with your feet flat on the ground, with your knees bent at 90 degrees. Alternatively, you can place your feet up on a bench a few inches apart with your toes turned inwards and touching.",
            "Place your hands lightly on either side of your head.",
            "Keep your elbows in  so that they are parallel to your body.",
            "Push your back down flat into the floor to isolate your abdominal muscles.",
            "Gently curl your shoulders forward and up off the floor.",
            "Continue to push down into the floor with your lower back.",
            "Raise your shoulders about four to six inches only.",
            "Hold and squeeze your abdominal muscles for a count of one.",
            "Return to the start position in a smooth movement.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32335&a=1",
    },
    {
        "title": "Hanging Leg Raises",
        "equipment": "Full gym",
        "primary": ["Abs"],
        "secondary": ["Forearms", "Glutes & Hip Flexors"],
        "description": [
            "Grip a chin up or pull up bar with a firm overhand grip.",
            "Hang from the bar with your legs straight.",
            "Raise your legs by flexing your hips forward and bending your knees up towards your chest.",
            "Continue to raise your knees towards your chest by flexing your waist forward. Don’t swing your body to use momentum. Use your abdominals to pull your legs up.",
            "Return to the starting position, lowering your legs slowly until they are straight.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31631&a=1",
    },
    {
        "title": "Barbell Curls / Standing Biceps Curls",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Biceps"],
        "secondary": ["Forearms"],
        "description": [
            "Stand straight holding a barbell with an underhand grip, your hands shoulder width apart and your arms fully extended towards the floor.",
            "Keep your elbows close to your sides.Your palms should be facing away from you. This is the start position.",
            "Keeping your upper arms stationary, curl the barbell forward and up in a smooth arcing motion while exhaling. Only your forearms should move.",
            "Continue upwards until  the bar is at shoulder level with your biceps fully contracted. Hold for a count of one while squeezing your biceps.",
            "Inhale as you return to the starting position.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31031&a=1",
    },
    {
        "title": "Barbell Drag Bicep Curls",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Biceps"],
        "secondary": ["Forearms"],
        "description": [
            "With a slight bend at the knee, hold the barbell extended towards the floor with an underhand grip about shoulder width apart.",
            "Push your elbows backwards allowing them to bend and the barbell to raise, running along the front of your torso.",
            "Continue with this motion until the barbell rests just above the nipple line and hold this position for a full second while flexing your biceps.",
            "Extend your elbows, slowly, allowing the barbell to again run along the body until rests in the starting position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31039&a=1",
    },
    {
        "title": "Cable Hammer Bicep Curls",
        "equipment": "Cable station",
        "primary": ["Biceps"],
        "secondary": ["Forearms"],
        "description": [
            "Stand at the cable station with your feet shoulder width apart and with a slight bend at the knee. ",
            "Grasp the rope with both hands and your palms facing inward.",
            "Keeping your core strong and your elbows fixed at your sides pull the rope towards the top of your chest (only the lower portion of your arms should be moving).",
            "Tense your biceps at the peak, and then slowly allow the rope to be pulled back down to the starting position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31271&a=1",
    },
    {
        "title": "Machine Bicep Preacher / Concentration Curls",
        "equipment": "Full gym",
        "primary": ["Biceps"],
        "secondary": ["Forearms"],
        "description": [
            "Adjust the seat height so that you can comfortably hang your arms over the pad of the machine. Make sure your shoulders are forward, allowing you to bring your arms closer than shoulder-width.",
            "Using an underhand grip, secure the handle of the machine bar. Keep a slight bend in the elbows at all times. Move the bar up, towards your face, focusing the tension in the biceps. Pause at the top and slowly lower to the starting position.",
            "Do not allow the weight to touch the stack and do not lock out your elbows. Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31835&a=1",
    },
    {
        "title": "EZ-Bar Preacher Curls",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Biceps"],
        "secondary": ["Forearms"],
        "description": [
            "Set up a preacher curl bench making sure that the seat is set at the right height for you. The seat shouldn’t be so low that you need to raise your shoulders, or so high that you need to lean over the support pad.",
            "Rest you arms on the support pad with your triceps near the top and your elbows midway down the pad.",
            "Grip the EZ curl bar with an underhand grip at shoulder width.",
            "Curl the bar in towards your chin and upper chest in a single smooth arc. Hold for a count of one.",
            "Lower the bar by extending your arms back to the starting position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31519&a=1",
    },
    {
        "title": "One-Arm Dumbbell Preacher Curl",
        "equipment": "Dumbbells",
        "primary": ["Biceps"],
        "secondary": ["Forearms"],
        "description": [
            "Set up a preacher curl bench making sure that the seat is set at the right height for you. The seat shouldn’t be so low that you need to raise your shoulders, or so high that you need to lean over the support pad.",
            "Rest you arm on the support pad with your triceps near the top and your elbow midway down the pad.",
            "Grip the dumbbell with an underhand grip at shoulder width.",
            "Curl the dumbbell in towards your chin and upper chest in a single smooth arc. Hold for a count of one while squeezing your biceps.",
            "Lower the dumbbell by extending your arms back to the starting position.",
            "Repeat for the desired number of repetitions then change to your other arm.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31935&a=1",
    },
    {
        "title": "Overhead Cable Curl / Crucifix Curls",
        "equipment": "Cable station",
        "primary": ["Biceps"],
        "secondary": ["Abs"],
        "description": [
            "Set up a cable station by adjusting the pulley height on each side to a little higher than shoulder height.",
            "Attach a stirrup type handle to each pulley.",
            "Select aweight that is comfortable, making sure the weight is the same on both sides of the machine.",
            "Stand between the two weight stacks of the machine,with your feet shoulder width apart.",
            "Extend your arms fully to your sides and grip the handles with an underhand grip.",
            "Make sure your arms and shoulders are in a straight line and alligned with the handles. This is the start position",
            "Exhale and contract your biceps to curl your forearms towards your shoulders.",
            "Continue until your forearms and biceps touch. Hold for a count of one while squeezing your biceps.",
            "Return to the star position in a smooth action while inhaling.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31951&a=1",
    },
    {
        "title": "Seated Alternating Incline Bench Dumbbell Curls",
        "equipment": "Dumbbells",
        "primary": ["Biceps"],
        "secondary": ["Abs", "Forearms"],
        "description": [
            "Set up an incline bench at 45 degrees.",
            "Holding a dumbbell in each hand, sit on the bench, keeping your shoulders and back firmly against the back rest.",
            "Put your arms down by your side with your palms facing in to your body.",
            "Slowly curl your arms up, rotating your wrist outwards (thumbs pointing away from your body) until the dumbbell is level with your shoulders. (Your palms should be facing your shoulders)",
            "Flex or squeeze your bicep at the top of the movement and hold for a count of one.",
            "Slowly lower the dumbbells back to the start position, turning your palms back in to your body. Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=30983&a=1",
    },
    {
        "title": "Seated Dumbbell Concentration Curls",
        "equipment": "Dumbbells",
        "primary": ["Biceps"],
        "secondary": ["Forearms"],
        "description": [
            "Sit on a flat bench with your legs spread, knees bent and your feet flat on the floor with a dumbbell between your feet.",
            "Use either arm to pick the dumbbell up and hold it with an underhand grip.",
            "Place the back of that upper arm on the top of your inner thigh on the same side. Your palm should be facing away from your thigh.",
            "Keep your arm fully extended downwards without letting the dumbbell rest on the floor. This is the start position.",
            "Curl the dumbbell forward and up in a smooth arc, contracting your biceps and exhaling.",
            "Continue curling the dumbbell upward until your biceps are fully contracted and the dumbbell is at shoulder level.  Hold for a count of one while squeezing your biceps.",
            "Return to the start position in a controlled, smooth arc inhaling as you do so. Do not swing the dumbbell down.",
            "Repeat for all the repetitions for that arm then switch and repeat the movement with your other arm.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31327&a=1",
    },
    {
        "title": "Standing Dumbbell Bicep Hammer Curls",
        "equipment": "Dumbbells",
        "primary": ["Biceps"],
        "secondary": ["Forearms"],
        "description": [
            "Stand straight holing a dumbbell in each hand with a neutral grip.",
            "Keep your arms fully extended with your palms facing in to your sides.",
            "Keep your elbows tucked in to your sides. This is the start position.",
            "Keeping your upper arm stationary, exhale and curl the dumbbells up towards your shoulders.",
            "Continue  raising the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.",
            "Hold for a count of one and squeeze your biceps.",
            "Return to the start position in a smooth movement, inhaling as you do so.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31615&a=1",
    },
    {
        "title": "180 / Twisting Jump Squats",
        "equipment": "NO EQUIPMENT",
        "primary": ["Calves", "Hamstrings", "Quadriceps"],
        "secondary": ["Abs", "Glutes & Hip Flexors"],
        "description": [
            "Begin standing tall with a tight core. Your chest will be up and your gaze will be straight ahead. Bend at the knees and drive your hips back as you lower yourself into a squat position.",
            "Launch yourself up while simultaneously twisting to the other side. Your body will perform a 180 degree turn in midair.",
            "Land with bent knees and immediately go right into another jump squat, turning to the starting position. Repeat this alternating pattern.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=30963&a=1",
    },
    {
        "title": "Agility Ladder Drills",
        "equipment": "Agility Ladder",
        "primary": [
            "Abs",
            "Calves",
            "Glutes & Hip Flexors",
            "Hamstrings",
            "Lower Back",
            "Quadriceps",
        ],
        "secondary": ["Biceps", "Shoulders", "Triceps"],
        "description": [
            "Lay out the agility ladder on a non-slip surface. ",
            "Perform a routine of choice. ",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31431&a=1",
    },
    {
        "title": "Bodyweight Calf Raises",
        "equipment": "NO EQUIPMENT",
        "primary": ["Calves"],
        "secondary": [],
        "description": [],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31171&a=1",
    },
    {
        "title": "Jumping Calf Presses / Raises",
        "equipment": "NO EQUIPMENT",
        "primary": ["Calves"],
        "secondary": [],
        "description": [],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31715&a=1",
    },
    {
        "title": "Rope Jumping / Jump rope / Skipping",
        "equipment": "NO EQUIPMENT",
        "primary": ["Calves", "Glutes & Hip Flexors"],
        "secondary": ["Abs", "Hamstrings", "Quadriceps"],
        "description": [
            "Hold one rope end in each hand out to your sides with the middle of the rope behind you.",
            "Keep the rope ends even with your hips.",
            "Rotate your wrists to swing the rope up over your head.",
            "As the rope  swings down in front of and towards you, jump over the rope with both feet.",
            "Continue rotating your wrists to swing the rope behind you, back up over your head to repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32171&a=1",
    },
    {
        "title": "Seated Calf Raises",
        "equipment": "Full gym",
        "primary": ["Calves"],
        "secondary": [],
        "description": [
            "Sitting on a calf raise machine, position your upper thighs under the top pad. The pad should be resting just above your knees.",
            "Place the balls of your feet on the foot plate.",
            "Keeping the balls of you feet in position, lower your heels as far as possible.",
            "Slowly raise your heels as if standing on your toes. Continue as far as possible until you feel a stretch in your lower calves. Hold for a count of one.",
            "Slowly lower your heels back to the starting position and repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32195&a=1",
    },
    {
        "title": "Leg Press Machine Calf Raises",
        "equipment": "Full gym",
        "primary": ["Calves"],
        "secondary": ["Quadriceps"],
        "description": [
            "Find a comfortable position on a leg-press machine with your feet placed, flat, about shoulder width apart.",
            "Extend the resistance away from your body until your knees are at an almost locked position (never fully lock your knees). ",
            "Further extend the platform away from your body, by driving your toes forward, into a tip-toe position.",
            "Hold this fully-extended position for 1 second, before lowering the platform to your extended-leg, flat-footed position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31295&a=1",
    },
    {
        "title": "Standing Barbell Calf Raises",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Calves"],
        "secondary": ["Abs"],
        "description": [
            "Set up two weight plates on the ground next to each other. Position a loaded barbell across your trap muscles. Step on to the weight plates with the heels of your feet.",
            "With a tight core and flat back, raise yourself up with your feet only. Pause at the top of the raise.",
            "Slowly lower yourself down but do not touch the ground. Raise yourself back up.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32751&a=1",
    },
    {
        "title": "Straight-Leg Calf Stretch",
        "equipment": "NO EQUIPMENT",
        "primary": ["Calves"],
        "secondary": [],
        "description": [
            "Stand a few inches away from a wall, facing it and place both hands on the wall with your arms extended.",
            "Lean against the wall and bend on leg forward with the other leg extended straight back. Your feet should both be facing forward.",
            "Push the rear heal to the floor and bring the hips slightly forward.",
            "Hold the stretch and repeat on the other leg.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32311&a=1",
    },
    {
        "title": "Standing Dumbbell Calf Raises",
        "equipment": "Dumbbells",
        "primary": ["Calves"],
        "secondary": [],
        "description": [
            "Place an exercise step or something similar on the floor in front of you. It should be two or three inches high.",
            "Holding a dumbbell in each hand, place your toes and the balls of your feet on the step. Make sure the arches of your feet are not on the step and your heels are on the floor.",
            "Raise your heels as high as possible by pushing through the balls of your feet and toes while extending your ankles. Hold for a count of one.",
            "Return to the starting position by bending your ankles until you feel a stretch in your calves.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32427&a=1",
    },
    {
        "title": "Barbell Bench Press / Chest Press",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Chest"],
        "secondary": ["Shoulders", "Triceps"],
        "description": [
            "Position yourself with your back down on a flat bench placing the hands up on the bar using an underhand grip slightly wider than shoulder width apart.",
            "After taking a deep breath in, extend the elbows and lift the bar up off the rack until elbows are extended but not locked. Pause for a brief movement as you fully extend your breath.",
            "Lower the weight directly down to the chest as you breath inwards, keeping the movement pattern slow and steady.",
            "Once just above the chest, pause, and then press directly up again, exhaling your breath.",
            "Continue until all reps are completed and then re-rack the barbell.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31019&a=1",
    },
    {
        "title": "Barbell Pullovers / Lying Chest Overhead Extensions",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Chest", "Upper Back & Lower Traps"],
        "secondary": ["Abs", "Shoulders", "Triceps"],
        "description": [
            "Lie on a flat bench, holding a barbell on your chest with an overhand grip. (Your hands should be shoulder width apart)",
            "Get into starting position, raising the bar above your chest by extending your arms, but do NOT lock your elbows.",
            "Keeping your arms slightly bent, slower lower the weight in a smooth arc to a position behind your head by rotating your shoulders. (as if putting your hands in the air)",
            "Keep moving the barbell behind your head until you feel a slight stretch in your chest. Hold for a count of one.",
            "Return to the start position in a smooth revers arc.",
            "Continue holding the weight above your chest, then repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31071&a=1",
    },
    {
        "title": "Butterflies / Pec Deck / Seated Machine Flyes",
        "equipment": "Full gym",
        "primary": ["Chest"],
        "secondary": ["Shoulders", "Triceps"],
        "description": [
            "Sit on a pec deck machine with your back flat against the back rest.",
            "Grip the handles and make sure your arms are parallel to the floor. If not parallel,adjust the seat or handles accordingly. This is the start position.",
            "Exhale and slowly push the handles together  squeezing your chest to the middle as you do so. Hold for a count of one.",
            "Inhale as you return to the starting position in a controlled movement.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31259&a=1",
    },
    {
        "title": "Decline Barbell Bench Press",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Chest"],
        "secondary": ["Abs", "Shoulders", "Triceps"],
        "description": [
            "Set a barbell in a weight rack at the low end of a decline bench,making sure it is at a height you can reach without fully extending your arms.",
            "Secure your feet under the stirrup, bar or strap at the high end of the bench and lie flat on your back with the rack slightly behind you.",
            "Using an overhand grip, grip the bar with your hands about twice your shoulder width apart.",
            "Push up to lift the bar from the rack and hold it directly over you with your arms locked. Your arms should be at 90 degrees to the floor. This is the start position.",
            "Bend your elbows to slowly lower the barbell until it touches our chest, inhaling as you do so.",
            "Hold for a count of one.",
            "Return to the start position by pushing the bar using your chest muscles, exhaling as you do so.",
            "At the top of the movement, lock your arms and squeeze your chest muscles.",
            "Hold for a count of one. Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31367&a=1",
    },
    {
        "title": "Decline Bench Dumbbell Press",
        "equipment": "Dumbbells",
        "primary": ["Chest"],
        "secondary": ["Shoulders", "Triceps"],
        "description": [
            "Sit on a decline bench and place your feet under the leg brace. Rest a dumbbell on each thigh.",
            "Grab hold of the dumbbells with an overhand grip and lie back on the bench.",
            "Position the dumbbells on either side of your chest. Your palms should face outwards and your arms should be bent under each weight.",
            "Slowly press the dumbbells up from the elbows until your arms are fully extended over your chest.",
            "Return to the starting position by lowering the dumbbells to either side of your chest again. You should feel a slight stretch in your chest and shoulders.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31363&a=1",
    },
    {
        "title": "Dumbbell Pullovers",
        "equipment": "Dumbbells",
        "primary": ["Chest", "Upper Back & Lower Traps"],
        "secondary": ["Abs", "Shoulders", "Triceps"],
        "description": [
            "Lie with your upper back perpendicular on a bench.",
            "Bend your knees and place your feet flat on the floor and flex your hips so that your body is in line.",
            "Grasp a dumbbell between your hands under the inner plate, palms facing up.",
            "Position the weight over your chest with your elbows slightly bent.",
            "Keep your elbows bent as you lower the dumbbell over your head until your upper arms are in line with your torso.",
            "To return to the starting position, pull the dumbbell up and over your chest.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31459&a=1",
    },
    {
        "title": "Incline Barbell Bench Chest Press",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Chest"],
        "secondary": ["Abs", "Shoulders", "Triceps"],
        "description": [
            "Set up an incline bench in front of a weight rack, making sure you adjust the incline to a comfortable position. The back of the bench should be facing the weight stack.",
            "Sit on the bench placing your back firmly against the backrest.",
            "Using an overhand grip, grasp the bar with your hands spaced about twice your shoulder width apart.",
            "Lift the bar from the rack by pushing up with your chest muscles and hold it straight over your chest with your arms fully extended. This is the start position.",
            "As you inhale, lower the barbell slowly until it touches your upper chest.",
            "Hold for a count of one while squeezing your chest muscles.",
            "Return to the start position as you exhale, pushing the bar using your chest muscles. Hold for a count of one.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31675&a=1",
    },
    {
        "title": "Incline Dumbbell Bench Chest Press",
        "equipment": "Dumbbells",
        "primary": ["Chest"],
        "secondary": ["Abs", "Shoulders", "Triceps"],
        "description": [
            "Set up an incline bench so the back rest is at about a 45 degree angle.",
            "Hold a dumbbell in each hand with an overhand grip. (Palms facing away from you)",
            "Sit on the bench with your feet flat on the floor and your back and shoulders pressed firmly back against the back rest.",
            "Raise the dumbbells up to your shoulder level, keeping your elbows bent at 90 degrees.",
            "Push the dumbbells up and away from you using your shoulders and chest while straightening your arms.",
            "Continue raising the dumbbells until your arms are straight and the dumbbells are suspended above your chest. Hold for a count of one.",
            "Lower the dumbbells back towards your chest by relaxing your chest and shoulders while bending your elbows.",
            "Hold for a count of one",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31687&a=1",
    },
    {
        "title": "Standing Cable Crossover Press / Flyes",
        "equipment": "Cable station",
        "primary": ["Chest"],
        "secondary": ["Abs", "Shoulders", "Triceps"],
        "description": [
            "Stand between two cable stations with the dumbbell grip handles attached to the high pulleys on each side of you.",
            "Hold the handles with an overhand grip. Your arms should be outstretched.",
            "Bend your knees and hips slightly so that you are leaning forward, but not too far.",
            "Bend your elbows slightly and rotate your shoulders in towards the centre of your chest a little. Your elbows should be slightly behind you.",
            "Use a hugging motion, keeping your elbows in a fixed, bent position to bring the grip attachments together in front of your chest.",
            "Slowly return to the starting position until you feel a slight stretch in your chest muscles.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32419&a=1",
    },
    {
        "title": "Static Push-up / Pushup Hold",
        "equipment": "NO EQUIPMENT",
        "primary": ["Abs", "Chest"],
        "secondary": ["Abs", "Shoulders", "Triceps"],
        "description": [
            "Position yourself in a plank position, supporting your body with your toes and place your hands underneath your shoulders with elbows extended. Keep your abs engage and prevent letting your hips sag.",
            "Lower your chest to the floor and hold for 30 seconds.",
            "Straighten up to starting position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31991&a=1",
    },
    {
        "title": "Adductor / Adduction Inner Thigh Machine",
        "equipment": "Full gym",
        "primary": ["Glutes & Hip Flexors"],
        "secondary": [],
        "description": [
            "Set up an adductor machine by selecting and appropriate weight and adjusting the seat and leg pads to a comfortable position.",
            "If fitted, grasp the handles on each side of the machine.",
            "Keep your entire upper body straight and stationary with your back pressed firmly against the back rest. This is the start position.",
            "While exhaling, press against the legs pads of the machine with your legs, and bring your thighs close together.",
            "When you feel a slight stretching in your adductors, pause for a count of one squeezing them as you do so.",
            "In a controlled movement, return to the start position, inhaling as you do so.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32611&a=1",
    },
    {
        "title": "Barbell Box Squats",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Glutes & Hip Flexors", "Hamstrings", "Quadriceps"],
        "secondary": ["Calves"],
        "description": [
            "Begin by positioning a barbell at or just below shoulder level in the squat rack. Behind the squat rack, place a tall wooden box or chair. Place yourself underneath the barbell. Make sure the bar is across your upper traps and NOT on your neck.",
            "Place your feet outside of shoulder-width with your toes pointed slightly out. Brace your core and keep your chest up.",
            "Bend at the knees as you drive your hips back. Lower yourself slowly until your butt touches the box. Pause then drive your hips forward to return to the starting position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31023&a=1",
    },
    {
        "title": "Barbell Hip Thrusts",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Glutes & Hip Flexors"],
        "secondary": ["Abs"],
        "description": [
            "Sit on a padded surface with your legs out in front of you and the knees bent. Make sure your back is against a secured bench. Lay a barbell across your lap.",
            "Focusing the tension in the glutes, raise your hips skyward, moving the bar up with you.",
            "Pause when you feel the contraction in your glutes then slowly lower yourself to the starting position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31059&a=1",
    },
    {
        "title": "Barbell Squats",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Glutes & Hip Flexors", "Quadriceps"],
        "secondary": ["Abs", "Calves", "Hamstrings", "Lower Back"],
        "description": [
            "Set up the barbell on the squat rack so that it is at the same height as your upper chest.",
            "Position your body under the bar, with knees bent so that the bar is resting high on the back of your shoulders.",
            "Grip the bar with your hands comfortably wider than your shoulders.",
            "Slowly straighten your legs to push upwards, lifting the barbell from the rack and take one step forward.",
            "Stand with your legs shoulder width apart.",
            "Bend your knees forward and allow your hips to bend back as if sitting down,",
            "Continue this movement down until your thighs are parallel to the floor or slightly more, making sure your knees are pointing in the same direction as your feet.",
            "Hold for a count of one.",
            "Push up through your heels while straightening your hips and knees, until you are standing in the start position.",
            "Make any adjustments necessary to your stance and grip before continuing on the next repetition.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31011&a=1",
    },
    {
        "title": "Cable Pull Throughs/Pulls",
        "equipment": "Cable station",
        "primary": ["Glutes & Hip Flexors"],
        "secondary": ["Hamstrings"],
        "description": [
            "With your back facing the cable station and the cable resting on the floor between your feet, bend at your knees and take a firm grip of the cable in both hands.",
            "Keeping your knees bent at a 45 degree angle, pull the cable up so that it is resting between your knees.",
            "With a firm grip on the cable extend your knees and drive your body upwards using your glutes as the prime mover.",
            "Hold the top portion while tensing your glutes.",
            "Slowly lower yourself back down to the starting position to complete 1 rep.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=38551&a=1",
    },
    {
        "title": "Front Barbell Squats",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Glutes & Hip Flexors", "Quadriceps"],
        "secondary": ["Abs", "Calves", "Hamstrings"],
        "description": [
            "Position yourself under a barbell held by a squat rack. Keeping your elbows high, place your arms up and under the bar. The bar should be resting on the front of your shoulders. Core is tight. Back is flat.",
            "Maintaining control, lift the bar up. Bend your knees forward and allow your hips to bend back as if sitting down. Pause when thighs are parallel with the floor.",
            "Return to the starting position and repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31591&a=1",
    },
    {
        "title": "Jump Squats",
        "equipment": "NO EQUIPMENT",
        "primary": ["Glutes & Hip Flexors", "Quadriceps"],
        "secondary": ["Abs", "Calves", "Hamstrings"],
        "description": [
            "Stand with your feet hip width apart. Your toes should be pointing straight ahead or only slightly outward.",
            "Cross your arms in front of your body, place your hands behind your head or at the sides of your head.",
            "Keep your weight on your heels and bend your knees while lowering your hips towards the ground as if you are sitting down on a chair.",
            "Keep your back straight at all times.",
            "Continue until you feel a slight stretch in your quadriceps. Do not let your knees extend out beyond the level of your toes.",
            "Pause for a count of one.",
            "In an explosive movement, drive down through your heels pushing yourself up of the floor with your quads.",
            "At the same time extend our arms out above you.",
            "Land with your knees slightly bent to absorb the impact.",
            "Repeat",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31711&a=1",
    },
    {
        "title": "Hip Raises / Butt Lift / Bridges",
        "equipment": "NO EQUIPMENT",
        "primary": ["Glutes & Hip Flexors", "Hamstrings"],
        "secondary": ["Abs", "Lower Back"],
        "description": [
            "Lie on an exercise mat with your knees bent so that your feet are flat on the floor. Keep your back straight.",
            "Place your hands out to your sides palms flat for stability.",
            "Raise your glutes off the floor by extending your hips upward while pushing down through you heels.",
            "Continue until your back, hips and thighs are in a straight line. Hold for a count of one.",
            "Return to the start position by lowering your hips back to the floor.",
            "Pause then repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31667&a=1",
    },
    {
        "title": "Bodyweight Squats",
        "equipment": "NO EQUIPMENT",
        "primary": ["Glutes & Hip Flexors", "Quadriceps"],
        "secondary": ["Abs", "Calves", "Hamstrings"],
        "description": [
            "Stand with your feet hip width apart. Your toes should be pointing straight ahead or only slightly outward.",
            "Cross your arms in front of your body, place your hands behind your head (prisoner squat) or at the sides of your head.",
            " Keep your weight on your heels and bend your knees while lowering your hips towards the ground as if you are sitting down on a chair.",
            "Keep your back straight at all times.",
            "Continue until you feel a slight stretch in your quadriceps. Pause for a count of one. Do not let your knees extend out beyond the level of your toes.",
            "Return to the start position by pushing down through your heels and extending your hips forward until you are standing straight. Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31183&a=1",
    },
    {
        "title": "Butt Kicks",
        "equipment": "NO EQUIPMENT",
        "primary": ["Hamstrings", "Quadriceps"],
        "secondary": ["Glutes & Hip Flexors"],
        "description": [
            "Standing tall with a tight core and flat back, you will begin the dynamic stretching exercise as if you were running in place. Keep the knees slightly bent at all times.Start slowly and work up to a faster speed.",
            "Bring your left foot back and all the way up to the glutes. Return your left foot to the ground and repeat on the other side.",
            "Continue this back and forth motion, keeping your arms swinging in motion. ",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31255&a=1",
    },
    {
        "title": "Bodyweight Side Steps / Lateral Lunges",
        "equipment": "NO EQUIPMENT",
        "primary": ["Glutes & Hip Flexors", "Hamstrings", "Quadriceps"],
        "secondary": ["Abs", "Calves"],
        "description": [
            "Stand tall with a tight core and make sure your feet are shoulder-width apart. Bring your hands together for balance.",
            "Step directly to the left, leaving your right foot in place. Bend the left knee and pause once the upper left thigh is parallel to the ground. Your right leg should be completely straight.",
            "Contract the hamstring muscle then push off the ground to return to the starting position. Repeat on the right side. Alternate this movement.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31179&a=1",
    },
    {
        "title": "Dumbbell Step-Ups",
        "equipment": "Dumbbells",
        "primary": ["Hamstrings", "Quadriceps"],
        "secondary": ["Calves", "Glutes & Hip Flexors"],
        "description": [
            "Place a bench in front of you. Hold a pair of dumbbells and stand facing the bench. Brace your core and keep your gaze straight ahead.",
            "Bring your right knee up and step up on to the bench. Placing all of the effort in your right leg, bring your body up into a standing position on the bench.",
            "Slowly lower yourself to the starting position and switch legs.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31487&a=1",
    },
    {
        "title": "Hex / Trap Bar / Cage Deadlifts / Squats",
        "equipment": "Full gym",
        "primary": ["Hamstrings", "Lower Back", "Quadriceps"],
        "secondary": ["Abs"],
        "description": [
            "Step inside of a Hex Bar / Cage. Keep your feet at shoulder width. Brace your core throughout the movement. Keeping your chest up, bend at the knees. Slowly, lower yourself until you are able to grab the handles of the Hex Bar.",
            "Begin the movement by engaging the hamstrings. Straighten the knees and hips simultaneously. Drive the hips forward at the top of the movement.",
            "Return to the starting position by bending at the knees and driving your hips back. Do not allow your hips to drop below your knees.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31647&a=1",
    },
    {
        "title": "Lying Leg Curls",
        "equipment": "Full gym",
        "primary": ["Hamstrings"],
        "secondary": ["Glutes & Hip Flexors"],
        "description": [
            "Lie face down on a leg curl machine and lock your heels under the foot pad. Make sure your legs are fully extended and the foot pads are resting on the back of your ankles.",
            "If the machine is equipped with handles, grip them. If not, grip the front of the pad you are lying on.",
            "Remaining flat on the bench, with no arching of your spine, curl your legs up in a smooth arcing motion by bending your knees until your hamstrings are fully contracted. Hold for a count of one.",
            "Slowly lower your legs to the starting position in a smooth arcing motion.",
            "Repeat",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31819&a=1",
    },
    {
        "title": "Romanian Deadlifts",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Hamstrings"],
        "secondary": ["Abs", "Calves", "Glutes & Hip Flexors", "Lower Back"],
        "description": [
            "Standing tall with a tight core and flat back, hold a barbell or a pair of dumbbells in front of you. Hands should be slightly wider than shoulder-width.",
            "Maintaining a tight core and flat back, bend your knees slightly and push your hips back. Keep your arms extended and the weight close to the body. Once you feel the contraction in the back of your legs, slowly return to the starting position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32167&a=1",
    },
    {
        "title": "Seated Leg Curls",
        "equipment": "Full gym",
        "primary": ["Hamstrings"],
        "secondary": ["Glutes & Hip Flexors"],
        "description": [
            "Adjust the seated leg curl machine to position the footpad just above your heels.",
            "Sit upright and engage your abs as you position your legs in front of you.",
            "Begin to curly your legs back slowly towards you and flex your calf muscles as you do so.",
            "Return to the starting position by extending the legs in front of you again.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32207&a=1",
    },
    {
        "title": "Sled Push",
        "equipment": "Full gym",
        "primary": ["Glutes & Hip Flexors", "Hamstrings", "Quadriceps"],
        "secondary": ["Abs", "Calves", "Shoulders"],
        "description": [
            "Place an appropriate amount of weight on a resistance sled. Begin by placing both hands on the sled. Step back with your right leg. Bend your left knee and bring it towards the sled. With both feet on the ground, bend at the hips. This is the starting position.",
            "Beginning with your right leg, step forward towards the sled. Keep your arms straightened as you push the sled forward.",
            "Alternate stepping forward while contracting your core. Maintain a flat lower back and a lowered gaze.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32371&a=1",
    },
    {
        "title": "Back Extensions / Hyperextensions",
        "equipment": "Full gym",
        "primary": ["Lower Back"],
        "secondary": ["Glutes & Hip Flexors", "Hamstrings"],
        "description": [
            "Lie face down on a hyper extension bench with your upper thighs and lower hips on the support pad. You must be able to bend at the waist freely.",
            "Lock your ankles under the footpads.",
            "Start with your body in a straight line head to toe.",
            "Place your arms across your chest, behind or at the side of your head.",
            "Slowly bend forward by relacing your, back and abdominal muscles.",
            "Continue as far as possible without rounding your back or raising your thighs from the support pad. You should feel a slight stretch in your hamstrings.Hold for a count of one.",
            "Return to the start position by contracting your back and abdominal muscles until your body is once again straight. Do not arch your back up at the end of the movement. Pause and repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31003&a=1",
    },
    {
        "title": "Barbell Deadlifts",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Lower Back"],
        "secondary": [
            "Abs",
            "Calves",
            "Forearms",
            "Glutes & Hip Flexors",
            "Hamstrings",
            "Quadriceps",
            "Upper Back & Lower Traps",
        ],
        "description": [
            "Place a barbell in a clear space on the floor. (Make sure there are no obstructions in your way.",
            "Stand facing the barbell with your legs about 4-6 inches from the bar.",
            "Place your feet shoulder width apart.Your feet can be pointed straight ahead or turned outwards slightly.",
            "Squat down, keeping your back straight and grip the bar with an overhand grip at shoulder width.",
            "Keep your arms fully extended and stand up with the barbell.",
            "As you lift the barbell, your hips and shoulders should rise together and your back should be straight.",
            "As you reach the top of the lift and are standing straight, rotate your shoulders back slightly until you feel a slight stretch in them.",
            "Lower the barbell back to the floor in the same squatting motion you used to lift it.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31035&a=1",
    },
    {
        "title": "Bent Over Barbell Row from Floor/Barbell Row",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Lower Back", "Middle Back / Lats"],
        "secondary": ["Biceps", "Upper Back & Lower Traps"],
        "description": [
            "Set up a barbell on the floor and stand facing it with your legs slightly wider than shoulder width apart and your knees slightly bent.",
            "Bend forward at your waist and grip the barbell with an overhand grip.",
            "Keep your back straight and nearly parallel to the floor.",
            "Keep your head and neck straight. This is the start position.",
            "Without moving your torso, exhale and lift the barbell up towards you from the floor.",
            "Keep your elbows close in to your body and use your forearms to support the weight.",
            "At the top of the movement, hold for a count of one and squeeze your back muscles.",
            "Return the barbell back to the floor as the start position, inhaling as you do so.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=36421&a=1",
    },
    {
        "title": "Barbell Good Morning",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Lower Back"],
        "secondary": ["Abs", "Glutes & Hip Flexors", "Hamstrings"],
        "description": [
            "Using a squat or barbell rack, set the barbell at shoulder height.",
            "Position yourself so the barbell is resting on your shoulders and you are facing away from the rack.",
            "Stand up to lift the barbell clear of the rack and take a few steps away from the rack.",
            "Position your feet slightly less than shoulder width apart.",
            "Keep your legs straight and bend forward at the hips.",
            "Continue bending forward until you feel a mild stretch in your hamstrings. (Do not try to bend past the mild stretching sensation. As flexibility increases so does the range of motion.) Hold for a count of one.",
            "Return to the starting position by straightening from the hips. Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31047&a=1",
    },
    {
        "title": "Dumbbell Deadlifts",
        "equipment": "Dumbbells",
        "primary": ["Glutes & Hip Flexors", "Lower Back"],
        "secondary": ["Abs", "Calves", "Hamstrings", "Quadriceps"],
        "description": [
            "Place two dumbbells on the floor.",
            "Stand facing the dumbbells with your feet shoulder width apart.",
            "Bend knees and hips to lower your torso in a squatting movement,keep your back straight.",
            "At the bottom of the squat grip the dumbbells with an overhand grip,keeping your arms fully extended.",
            "Return to an upright position holding the dumbbells with your palms facing towards your body and extending your hips forward. Do not round your back.",
            "Return the dumbbells to the floor in the same manner you picked them up.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31439&a=1",
    },
    {
        "title": "Kettlebell Deadlifts",
        "equipment": "Kettlebells",
        "primary": ["Abs", "Hamstrings", "Lower Back"],
        "secondary": ["Calves", "Obliques", "Shoulders"],
        "description": [
            "Place a kettlebell on the ground. Step over the kettlebell so that it is in the center beneath you. Move your feet to shoulder-width or just outside of shoulder-width. Tighten your core and keep your chest up.",
            "Begin by kicking your hips back and slightly bending your knees. Extend your arms down to grab onto the kettlebell. ",
            "Holding on to the kettlebell, drive your hips forward to stand back up. Slowly, reverse the movement by kicking your hips back and slightly bending the knees. Do not let your lower back arch.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31727&a=1",
    },
    {
        "title": "Kettlebell One-Legged Deadlifts",
        "equipment": "Kettlebells",
        "primary": ["Lower Back"],
        "secondary": ["Abs", "Glutes & Hip Flexors", "Hamstrings"],
        "description": [
            "Hold a kettlebell by the handle in one hand using a neutral grip.",
            "Stand on the leg that is on the same side that you are holding the kettlebell.This is the start position.",
            "Bending that knee slightly, bend at the hip, and extend your free leg behind you for balance.",
            "Continue lowering the kettlebell until your torso is parallel to the ground.",
            "Return to the upright position in a smooth movement.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31731&a=1",
    },
    {
        "title": "Stability / Swiss / Exercise Ball Back Extensions",
        "equipment": "Swiss / Exercise ball",
        "primary": ["Lower Back"],
        "secondary": [],
        "description": [
            "Lie prone on a swiss ball with your feet hip width apart. You can place your feet against a wall for better stability. Clasp your hands behind your head with elbows pointing out.",
            "Engage your abs and raise your torso off the ball, hyperextending your spine.",
            "Return your torso to the ball to the starting position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32519&a=1",
    },
    {
        "title": "Supermans / Extended Arms & Legs Lifts",
        "equipment": "NO EQUIPMENT",
        "primary": ["Lower Back"],
        "secondary": ["Abs"],
        "description": [
            "Lie face down on a mat, with your arms fully extended above your head and your legs fully extended behind you.",
            "Lift your chest, arms and legs off the floor by arching your back. Only the tops of your quads and your lower abdomen should be in contact with the floor.",
            "Hold for a count of 2 while squeezing your abdominals and obliques.",
            "Return to the starting position for a count of one, then repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32491&a=1",
    },
    {
        "title": "Bent Over Barbell Rows",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Lower Back", "Middle Back / Lats"],
        "secondary": ["Abs", "Biceps", "Forearms", "Upper Back & Lower Traps"],
        "description": [
            "Set up a barbell on the floor and stand facing it with your legs slightly wider than shoulder width apart and your knees slightly bent.",
            "Bend forward at your waist and grip the barbell with an overhand grip.",
            "Keep your back straight and nearly parallel to the floor.",
            "Keep your head and neck straight. This is the start position.",
            "Without moving your torso, exhale and lift the barbell up towards you.",
            "Keep your elbows close in to your bodyand use your forearms to support the weight.",
            "At the top of the movement, hold for a count of one and sqyeeze your back muscles.",
            "Return to the start position inhaling as you do so.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31147&a=1",
    },
    {
        "title": "Bent Over Two-Arm Long Barbell / T-Bar Rows",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Lower Back", "Middle Back / Lats"],
        "secondary": ["Abs", "Biceps", "Forearms", "Upper Back & Lower Traps"],
        "description": [
            "Set up an Olympic (long) barbell with weight plates on one end only.",
            "Put the other end of the bar against a wall or something heavy so it can’t slide backwards.",
            "Straddle the bar with your knees slightly bent.",
            "Bend forward at the waist until your torso is nearly parallel to the floor.",
            "Grip the bar close to the weight plates with both hands, using a neutral grip. One hand in front  the other. This is the start position.",
            "Keeping your back straight and exhaling, pull the bar straight up by bending your elbows until the plates touch your chest.",
            "Hold and squeeze your back muscles.",
            "Return to the start position in a slow smooth movement to place emphasis on your lats. Inhale as you do so.",
            "Keep the bar from touching the floor.",
            "pause then repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31155&a=1",
    },
    {
        "title": "Dumbbell Incline Bench Rows",
        "equipment": "Dumbbells",
        "primary": ["Lower Back", "Middle Back / Lats"],
        "secondary": ["Biceps", "Forearms", "Shoulders"],
        "description": [
            "Lean forward into an incline bench",
            "Using a neutral grip, hold a dumbbell in each hand so your palms are facing in.",
            "Your arms should be fully extended and hanging straight down. This is the start position.",
            "Pull your shoulder blades back and flex your elbows to pull the dumbbells up to your sides.",
            "Hold and squeeze your shoulder and back muscles.",
            "Return to the start position in a slow, controlled movement.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31447&a=1",
    },
    {
        "title": "Close Grip Lat Pulldowns / Pull Downs / Pullovers",
        "equipment": "Full gym",
        "primary": ["Middle Back / Lats"],
        "secondary": ["Biceps"],
        "description": [
            "Sit at a Lat Pulldown machine and secure your legs underneath the padded surface. Select an appropriate weight on the stack. Reach up to grab the barbell, taking a close-grip. Your hands should be at or closer than shoulder-width.",
            "Tighten your core and keep your chest up as you pull the barbell down and towards your chest. Be sure to pull with your lat muscles.",
            "Once the bar is at your chest, slowly allow it to return to the starting position but don’t let the weight stack touch. Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31319&a=1",
    },
    {
        "title": "Wide-Grip Lat Pulldowns / Pull Downs / Pullovers",
        "equipment": "Cable station",
        "primary": ["Lower Back", "Middle Back / Lats"],
        "secondary": ["Abs", "Biceps"],
        "description": [
            "Set up a cable station with a straight bar attached to the top pulley.",
            "Sit on the seat facing the station. Keep your feet flat and planted firmly on the floor.",
            "Using an overhand grip, hold the bar as wide as comfortable. (Your hands should be about 1 1/2 – 2 times body width apart.)",
            "Lean back slightly without arching your back.",
            "Pull the bar towards the top of your chest using your shoulders while arcing your elbows out to the sides of your body.",
            "At the end of the movement squeeze you shoulders together slightly and hold for a count of one.",
            "Return to the start position by arcing your elbows forward while relaxing your shoulders.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32711&a=1",
    },
    {
        "title": "Weighted Pull-Ups / Pullups",
        "equipment": "Full gym",
        "primary": ["Middle Back / Lats"],
        "secondary": ["Biceps"],
        "description": [
            "Carefully secure a weight belt around your hips. Stand below a pull-up bar. Reach up and secure your overhand grip. Brace your core.",
            "Begin the movement by pulling with your lat / middle back muscles to bring your body towards the bar.",
            "Once your chest nears the bar, pause to feel the contraction in your back then slowly lower yourself to the starting position. Do not lock out your elbows.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32695&a=1",
    },
    {
        "title": "Seated Machine Back Row",
        "equipment": "Full gym",
        "primary": ["Middle Back / Lats"],
        "secondary": ["Abs", "Biceps"],
        "description": [
            "Seat yourself at a Row Machine and select the appropriate weight. Sit up straight with a tight core. Reach forward and take an overhand grip on the bar in front of you. Activate your lats before the movement.",
            "Pull the bar towards you, emphasizing the lat movement. Pause when the bar is at your sides and squeeze your back.",
            "Slowly, return the bar to the starting position but do not set it down. Repeat the movement, ensuring your back is activated throughout.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31607&a=1",
    },
    {
        "title": "Machine Assisted Pull-ups / Pullups",
        "equipment": "Full gym",
        "primary": ["Middle Back / Lats"],
        "secondary": ["Biceps"],
        "description": [
            "Select the correct weight to counterbalance your own before beginning. The heavier the weight, the easier it will be.",
            "Reach above and use an overhand grip to secure yourself as you kneel on the padded surface of the assisted machine. Tighten your core as well as your glutes.",
            "Lower yourself slowly. Do not lock out the elbow. Pull yourself back to the starting position but do not let the weight touch the stack. Pause and repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31831&a=1",
    },
    {
        "title": "Gymnastic Ring Pull-Ups / Pullups",
        "equipment": "Gymnastic Rings",
        "primary": ["Middle Back / Lats", "Upper Back & Lower Traps"],
        "secondary": ["Biceps", "Forearms", "Shoulders"],
        "description": [
            "Stand directly beneath the Gymnastic Rings ensuring that they have enough height for you to lower your body without touching the ground. ",
            "Grip the rings so that your palms are facing inward.",
            "Pull your chest upwards and towards the rings by bending your arms. Aim to avoid any jerking movements as this may cause the rings to swing. ",
            "Once your chest is at its highest point, hold this position for one second before steadily lowering your body back down to the starting position. ",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31607&a=1",
    },
    {
        "title": "Barbell Lunges",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Quadriceps"],
        "secondary": ["Abs", "Calves", "Glutes & Hip Flexors", "Hamstrings"],
        "description": [
            "Set up a  barbell on a rack  at just below shoulder level.",
            "Step under the bar placing the back of your shoulders under it. Do not rest the bar on your neck.",
            "Grip the the bar using an overhand grip with your elbows bent to90 degrees or slightly more. Less of an angle means your hands are too close together which can cause instability of balance.",
            "Lift the barbell clear of the rack by  pushing with your legs, while straightening your torso.",
            "Step away from the rack.",
            "Step forward with your right leg and squat down through your hips. Keep your back straight  and be careful to maintain your balance. Inhale as you lower yourself.",
            "Continue lowering your body until your left knee is nearly touching the floor.",
            "Return to the start position b pushing through your heel,exhaling as you do so.",
            "Complete all the repetitions for one leg before switching.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31063&a=1",
    },
    {
        "title": "Barbell Overhead Squats",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Calves", "Hamstrings", "Quadriceps"],
        "secondary": ["Abs", "Shoulders"],
        "description": [
            "Place an appropriate amount of weight on a barbell in a squat rack. Position your hands in an overhand grip outside of shoulder-width on the barbell. Before beginning, make sure that your core is tight and your chest is up.",
            "Push the barbell straight above your head, locking out your elbows. Once you feel stabilized, slowly bend the knees and drive back your hips.",
            "Once your upper thighs come parallel with the ground, slowly push back up, returning to the starting position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31067&a=1",
    },
    {
        "title": "Barbell Split Squats",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Calves", "Hamstrings", "Quadriceps"],
        "secondary": ["Abs"],
        "description": [
            "Place an appropriate amount of weight on a barbell in a squat rack. Once ready, position yourself underneath the barbell. Keep your core tight and drive your hips forward to lift the barbell off the rack. Step away from the rack. Secure the barbell on your traps and make sure your core is braced before beginning.",
            "Step out with the left foot, leaving the right foot behind. From this position, lower the back right knee towards the ground. Push up with your front left leg. Please note that you will not kick back up into a regular standing position until all repetitions have been completed.",
            "Continue this up and down pattern. Switch sides and perform the same pattern with the right leg in front.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31091&a=1",
    },
    {
        "title": "Barbell Step-ups",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Glutes & Hip Flexors", "Quadriceps"],
        "secondary": ["Abs", "Calves"],
        "description": [
            "Set up a barbell in a rack at shoulder height.",
            "In front of the rack, place an aerobic or exercise step on the floor.",
            "Position yourself under the barbell so it is resting across your shoulder. Not on your neck.",
            "Stand up straight to lift the barbell from the rack and walk forward to the step.",
            "Place one foot on the step and push down through your heel while straightening your leg to lift yourself up onto the step and place your other foot flat on the step.Hold fora count of one.",
            "Step down with the opposite leg to the one you started the movement with.",
            "Repeat all the repetitions of the set for your chosen lead leg befor changing to the other.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31015&a=1",
    },
    {
        "title": "Bosu Ball Single Leg / Pistol Squats",
        "equipment": "Bosu ball",
        "primary": ["Hamstrings", "Quadriceps"],
        "secondary": ["Abs", "Calves"],
        "description": [
            "Place a BOSU on the ground with the soft blue side facing up. Tighten your core and keep your chest up.",
            "Carefully step on to the middle of the BOSU with the right foot. Once you are balanced, slowly extend the left leg in front of you.",
            "Bend at the right knee as you drive your hips back. Lower yourself and do not allow your hips to break parallel with the ground. Pause and return to the starting position. Complete your set and repeat on the other leg.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31227&a=1",
    },
    {
        "title": "Bulgarian Split Squats",
        "equipment": "Dumbbells",
        "primary": ["Quadriceps"],
        "secondary": ["Abs", "Calves", "Hamstrings"],
        "description": [
            "Stand up straight while holding two dumbbells. Maintain a tight core and flat back as you carefully place your right foot on top of a bench behind you with toes facing down. ",
            "Bend at the front knee as you drop the back knee, maintaining perfect form. Front knee should not go over the toes.",
            "Allow your thigh to come to parallel with the floor.",
            "Pause then slowly return to the starting position without locking out your knee.",
            "Repeat then switch sides once set is complete.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31247&a=1",
    },
    {
        "title": "Duck Walks / Squats",
        "equipment": "NO EQUIPMENT",
        "primary": ["Glutes & Hip Flexors", "Quadriceps"],
        "secondary": ["Hamstrings"],
        "description": [
            "Stand with your feet slightly wider than shoulder width apart. Bend your knees and bring yourself down into a squat until your thighs are parallel to the floor. ",
            "Keep your chest up, your eyes focused straight ahead, and your core engaged. ",
            "Take mini, duck-like steps forwards and backwards for the designated number of reps.",
            "Quack quack. ",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31419&a=1",
    },
    {
        "title": "Dumbbell Squats",
        "equipment": "Dumbbells",
        "primary": ["Quadriceps"],
        "secondary": ["Calves", "Glutes & Hip Flexors", "Hamstrings", "Lower Back"],
        "description": [
            "With your feet shoulder-width apart, stand with dumbbells as your sides with your palms facing each other.",
            "Keeping your back straight and facing forward, squat down until your thighs are parallel to the floor.",
            "Pause for one second.",
            "Pushing up from your heels, raise back up to starting position and repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31483&a=1",
    },
    {
        "title": "Dumbbell Squat Thrusters / Squat to Overhead Press",
        "equipment": "Dumbbells",
        "primary": ["Quadriceps", "Shoulders"],
        "secondary": [
            "Abs",
            "Glutes & Hip Flexors",
            "Hamstrings",
            "Neck & Upper Traps",
            "Triceps",
        ],
        "description": [
            "Stand with your feet shoulder-width apart with dumbbells above your shoulders.",
            "Squat down keeping your back flat and your knees over your toes.",
            "Push through your heels to return to standing while pressing the dumbbells overhead with arms fully extended.",
            "Return to starting position and repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32383&a=1",
    },
    {
        "title": "Front Barbell Squats",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Glutes & Hip Flexors", "Quadriceps"],
        "secondary": ["Abs", "Calves", "Hamstrings"],
        "description": [
            "Position yourself under a barbell held by a squat rack. Keeping your elbows high, place your arms up and under the bar. The bar should be resting on the front of your shoulders. Core is tight. Back is flat.",
            "Maintaining control, lift the bar up. Bend your knees forward and allow your hips to bend back as if sitting down. Pause when thighs are parallel with the floor.",
            "Return to the starting position and repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31591&a=1",
    },
    {
        "title": "High Box Jumps",
        "equipment": "Full gym",
        "primary": ["Glutes & Hip Flexors", "Quadriceps"],
        "secondary": ["Abs", "Calves"],
        "description": [
            "Stand in front of a sturdy bench, box or other flat non slip surface that’s high enough that you must use that you have to use a lot of effort in order to jump up on top of it.",
            "Stand with your feet shoulder width apart.",
            "Bend your knees as if crouching or performing a squat.",
            "In an explosive movement, push through your feet to jump up onto the landing area.",
            "Make a soft landing by bending your knees as your feet touch down.You should land on both feet simultaneously.",
            "Step down and repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31651&a=1",
    },
    {
        "title": "Barbell Push and Press",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Shoulders"],
        "secondary": ["Abs", "Glutes & Hip Flexors", "Quadriceps", "Triceps"],
        "description": [
            "Stand with feet hip width apart and grasp a barbell with an overhand grip.",
            "Make sure your hands are placed slightly wider than shoulder-width.",
            "Bring the bar to chest height and slightly retract your head back.",
            "Bend the knees, hips and ankles to dip slightly.",
            "Use your legs to explosively drive your body upwards and drive the barbell off your shoulders, extending your arms overhead.",
            "Lower the bar to your shoulders and repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32019&a=1",
    },
    {
        "title": "Barbell Shoulder Press / Overhead Press",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Shoulders"],
        "secondary": ["Abs", "Triceps", "Upper Back & Lower Traps"],
        "description": [
            "Place a bench with a back support inside a squat rack and set up a barbell at a height that is just above your head.",
            "Grip the barbell with an overhand grip.",
            "Space your hands out so that your elbows are bent at 90 degrees.",
            "Lift the bar to around shoulder level by extending your arms.  This is the start position.",
            "Inhaling, lower the bar  to your shoulders slowly.",
            "Hold for a count of one while squeezing your shoulder muscles.",
            "Push the barbell back to the start position as you exhaling as you do so..",
            "Repeat for the recommended amount of repetitions.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31079&a=1",
    },
    {
        "title": "Battle Rope Double Waves",
        "equipment": "Battle Rope",
        "primary": ["Abs", "Shoulders", "Upper Back & Lower Traps"],
        "secondary": ["Calves", "Hamstrings", "Quadriceps"],
        "description": [
            "Holding a battle rope in each hand, slightly bend at the knees and maintain a tight core.",
            "Synchronize the ropes to follow an up and down pattern.",
            "Bring the ropes upward together to your shoulder level then downward to hip level and immediately back up.",
            "Repeat the movement, ensuring you keep the ropes together.",
            "Do not lock out your elbows at any point during the exercise.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31107&a=1",
    },
    {
        "title": "Dual / Two Arm Dumbbell Front Shoulder Raises",
        "equipment": "Dumbbells",
        "primary": ["Neck & Upper Traps", "Shoulders"],
        "secondary": ["Abs"],
        "description": [
            "Holding a pair of dumbbells with an overhand grip, stand tall with your chest up and core braced. ",
            "Begin by lifting the dumbbells in front of you. Keep the abdominals contracted as you raise the dumbbells. Feel the contraction in the shoulder muscles.",
            "Once the dumbbells reach shoulder height, pause and slowly lower the dumbbells to the starting position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31415&a=1",
    },
    {
        "title": "Dumbbell Bent Over Lateral Rear Delt Raises / Flyes",
        "equipment": "Dumbbells",
        "primary": ["Shoulders"],
        "secondary": [],
        "description": [
            "Begin by holding a pair of dumbbells and standing with a braced core. Bend at the knees slightly and lean forward from the hips. Maintain a flat back throughout.",
            "Keeping your elbows slightly bent throughout the movement, lift the dumbbells up and out to the side. Be sure to focus the contraction in the back of the shoulders.",
            "Pause at the top of the movement then slowly bring the dumbbells to the starting position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32647&a=1",
    },
    {
        "title": "Dumbbell Overhead Shoulder Press",
        "equipment": "Dumbbells",
        "primary": ["Shoulders"],
        "secondary": ["Abs", "Triceps", "Upper Back & Lower Traps"],
        "description": [
            "Sit on a military press bench or bench that has a back support, holding a dumbbell in each hand with an overhand grip.",
            "Place the dumbbells on top of your thighs with your palms facing down.",
            "Raise the dumbbells to your shoulders.",
            "Rotate your wrists so that the palms of your hands are facing away from you. This is the start position.",
            "As you exhale,  push the dumbbells up and over your head by extending your arms until the dumbbells touch at the top of the movement.",
            "Pause for a count of one.",
            "Slowly return to the start position inhaling as you do so.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31467&a=1",
    },
    {
        "title": "Dumbbell Shrugs",
        "equipment": "Dumbbells",
        "primary": ["Shoulders"],
        "secondary": [],
        "description": [
            "Stand with your feet shoulder width apart and a dumbbell in each hand.",
            "Keep your arms extended and by your sides and with your palms facing in.",
            "Relax your shoulders so they hang as low as possible.",
            "Raise the dumbbells by slowly lifting your shoulders in a shrugging motion. Hold for a count of one.",
            "Slowly relax your shoulders to return to the start position.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31471&a=1",
    },
    {
        "title": "Forward / Front Shoulder Dumbbell Raises",
        "equipment": "Dumbbells",
        "primary": ["Shoulders"],
        "secondary": ["Abs"],
        "description": [
            "Stand straight holding a dumbbell in each hand with an overhand grip.",
            "Hold the dumbbells in in front of your thighs with your palms of the facing your thighs. Keep your arms fully extended. This is the start position.",
            "Raise the left dumbbell out and upwards, while keeping a slight bend in your elbow. Your palms must always face down for this exercise.",
            "Continue raising the dumbbell until you arm is a little above parallel to the floor. Exhale as you are raising the dumbbell.",
            "Pause for a count of one.",
            "Inhale and slowly lower the dumbbell to the start position.",
            "As you lower the left dumbbell, begin to lift the right dumbbell, duplicating the movement.",
            "When both dumbbells have been raised and lowered in a cycle, that is one repetition.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31575&a=1",
    },
    {
        "title": "Lateral / Side Shoulder Dumbbell Raises / Power Partials",
        "equipment": "Dumbbells",
        "primary": ["Shoulders"],
        "secondary": [],
        "description": [
            "Stand with your back straight, feet shoulder width apart, while holding a dumbbell in each hand with a neutral grip.",
            "Hold your arms fully extended by your side, with your palms facing in to your body.",
            "Keep your elbows close to your sides. This is the start position.",
            "Keeping your arms fully extended and your torso stationary, lift the dumbbells out to your sides and up until they are at shoulder level. Exhale as you do so.",
            "Hold for a count of one while squeezing your shoulder muscles.",
            " Return to the start position in a smooth controlled movement inhaling as you do so.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31451&a=1",
    },
    {
        "title": "Assisted / Machine Seated Tricep Dips",
        "equipment": "Full gym",
        "primary": ["Triceps"],
        "secondary": [],
        "description": [
            "Sit at the Triceps Dip machine but make sure to brace your core throughout the movement. Place your hands on the bar with your elbows pointing behind you. Your arms will make a 90 degree angle.",
            "Slowly push down on the bars, focusing all the movement in your triceps.",
            "When you reach the bottom, pause and do not lock out your elbows. Slowly return to the starting position but do not let the weight touch the stack.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=30999&a=1",
    },
    {
        "title": "Bent Over Double Arm Tricep Kickbacks",
        "equipment": "Dumbbells",
        "primary": ["Triceps"],
        "secondary": ["Abs", "Lower Back"],
        "description": [
            "Holding a pair of dumbbells with an overhand grip, stand tall with your chest up and core braced. Bend at the hips while keeping your back completely flat.",
            "Once your upper body is parallel with the floor, bring your upper arms to your sides. Begin by pushing the dumbbells back and behind you.",
            "Pause at the top of the movement and feel the contraction in your triceps. Slowly lower the dumbbells and begin again.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31151&a=1",
    },
    {
        "title": "Cable Rope Overhead Triceps Extensions",
        "equipment": "Cable station",
        "primary": ["Triceps"],
        "secondary": ["Forearms"],
        "description": [
            "Attach a rope to the bottom pulley of a cable station.",
            "Grip the rope with both hands using a neutral grip. Turn your body away from the cable station.",
            "Fully extend your arms until your hands are directly above your head pointing to the ceiling.",
            "Keep your elbows  close to your head. This is the start position.",
            "Slowly lower the rope behind your head, keeping your upper arms stationary, inhaling as you do so.",
            "When your triceps are fully extended, hold for a count of one while squeezing your triceps.",
            "Return to the starting position by flexing your triceps  and extending your arms. Exhale as you do so.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31283&a=1",
    },
    {
        "title": "Chair / Bench Tricep Dips",
        "equipment": "NO EQUIPMENT",
        "primary": ["Triceps"],
        "secondary": ["Shoulders"],
        "description": [
            "Sit on a chair with your hands either next to your hips or slightly under the hips.",
            "Lift up onto your hands and bring your hips forward.",
            "Bend your elbows and lower your hips down, keeping shoulders down and hips close to the chair.",
            "Push back up but don’t lock your elbows and repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31307&a=1",
    },
    {
        "title": "Diamond / Pyramid / Triceps Push-ups / Pushups",
        "equipment": "NO EQUIPMENT",
        "primary": ["Triceps"],
        "secondary": ["Abs", "Chest", "Shoulders"],
        "description": [
            "Position yourself on all fours on a mat.",
            "Place your hands in front of you and shoulder-width apart.",
            "Now bring your hands in towards the center until the tips of your index fingers and tips of your thumbs are touching. This creates a diamond shape between your hands. Your elbows and wrists should be in line with your chest.",
            "With your fingers facing forwards, lift off your knees so that your body forms a straight line and just your hands and toes touch the floor.",
            "Keep you pelvis straight and abs engaged and aim to keep a straight back throughout the movement.",
            "Bend your elbows and lower your body towards the floor, aiming to touch your chest to the top of your hands. Pause briefly.",
            "Return to the starting position by extending your elbows and lifting your body off the floor again.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31387&a=1",
    },
    {
        "title": "Flat Bench Barbell Skull Crushers",
        "equipment": "Barbell / EZ-Bar",
        "primary": ["Triceps"],
        "secondary": ["Abs"],
        "description": [
            "Holding a preacher curl barbell with an overhand grip, carefully sit on a bench. Slowly lie back and bring the barbell above your head. Make sure that your feet are flat on the floor and your core is braced.",
            "Keep the upper arms in place as you bend at the elbow and allow the forearms to slowly dip back towards your head.",
            "Once the barbell reaches the bottom, pause and slowly push the barbell back to the starting position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31531&a=1",
    },
    {
        "title": "Seated Single Arm Overhead Dumbbell Tricep Extensions",
        "equipment": "Dumbbells",
        "primary": ["Shoulders", "Triceps"],
        "secondary": [],
        "description": [
            "Sit on a bench while holding a dumbbell in your left hand with an overhand grip. Tighten your core and straighten your lower back. Lift the dumbbell to shoulder height.",
            "Push the dumbbell overhead with your palm facing forward. Keep the upper arm in place. Slowly bend at the elbow and lower the weight behind your head.",
            "Push the dumbbell back up over your head squeezing the tricep muscle. Immediately begin the next repetition. Switch sides once you have completed all repetitions.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32235&a=1",
    },
    {
        "title": "Seated Tricep Press / Overhead Extensions",
        "equipment": "Dumbbells",
        "primary": ["Triceps"],
        "secondary": ["Abs"],
        "description": [
            "Sit on a bench with back support.",
            "Grip a dumbbell at one end using both hands. Your palms should be facing inward.",
            "Hold the dumbbell overhead with your arms fully extended.  This is the the start position.",
            "Keep your upper arms close to your head (biceps roughly level with your temples) and near to 90degrees to the floor.",
            "Moving only your forearms, lower the dumbbell in a smooth arc behind your head until your forearms and biceps touch. Hold for a count of one.",
            "Return to the start position by using the triceps to extend your arm and raise the dumbbell. Exhale as you do this.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32239&a=1",
    },
    {
        "title": "Tricep Cable Rope Push /Pull Downs",
        "equipment": "Cable station",
        "primary": ["Triceps"],
        "secondary": ["Abs", "Forearms"],
        "description": [
            "Set up a cable station with a straight bar on attached to the top pulley.",
            "Grip the bar with an overhand grip,with your hands slightly less than shoulder width apart.",
            "Position your feet shoulder width apart,with knees slightly bent for stability.",
            "Pull the bar down until your forearms are parallel to the floor with your elbows close to your body and your wrists locked in a straight position. This is your staring point.",
            "Moving only your forearms, push the bar down towards the floor until your arms are fully extended and you feel a stretch in your triceps. Hold for a count of one and squeeze your triceps.",
            "Return to the start position moving your forearms only. Hold for a count of one then repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=32631&a=1",
    },
    {
        "title": "Triceps Dips",
        "equipment": "NO EQUIPMENT",
        "primary": ["Triceps"],
        "secondary": ["Chest", "Forearms", "Shoulders"],
        "description": [
            "Standing between the bars of a dip station, grip the bars with an overhand grip,keeping your elbows tucked in close to your body.",
            "Allow your body weigh to hang so it is being supported by your arms and shoulders. Keep your hips straight.",
            "Push down through your palms with your arms, lifting your body up until your arms are almost straight. (Do not lock your elbows)",
            "Lower your body by slowly bending your elbows and continue down until you feel a slight stretch in your shoulders.",
            "Pause, then push yourself back to the starting position.",
            "Repeat.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31391&a=1",
    },
    {
        "title": "Bent Over Water Bottle Flyes",
        "equipment": "Water Bottles",
        "primary": ["Upper Back & Lower Traps"],
        "secondary": ["Shoulders"],
        "description": [
            "Begin by holding a pair of water bottles and standing with a braced core. Bend at the knees slightly and lean forward from the hips. Maintain a flat back throughout.",
            "Keeping your elbows slightly bent throughout the movement, lift the water bottles up and out to the side. Be sure to focus the contraction in the back of the shoulders.",
            "Pause at the top of the movement then slowly bring the water bottles to the starting position.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=38414&a=1",
    },
    {
        "title": "One-Arm Kettlebell Rows",
        "equipment": "Kettlebells",
        "primary": ["Lower Back", "Upper Back & Lower Traps"],
        "secondary": ["Abs", "Biceps"],
        "description": [
            "Place a kettlebell in front of you",
            "Place your right leg forward and rest your left leg on the ball of your left foot.(Similar to a lunge stance)",
            "Bend your knees slightly as you bend over to get in the starting position.",
            "Keep your back straight.",
            "Rest your right hand on your right knee for stability.",
            "Grip the kettlebell with a neutral grip in your left hand.",
            "Pull the kettlebell up to your stomach, retracting your shoulder blade and flexing your elbow. Keep your back straight. Lower and repeat.",
            "Complete all the repetitions for one side before switching.",
        ],
        "img_url": "https://workoutlabs.com/train/svg.php?id=31919&a=1",
    },
]
